# Generated by Django 3.2 on 2022-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news_detection', '0008_newsarticle_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=90)),
                ('email', models.CharField(default='NULL', max_length=111)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
