# Generated by Django 3.2 on 2022-10-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_news_detection', '0009_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
